### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by SubhamPaul21**
updated .gitignore file

### CODE REVIEW

**Comment by ghost** [comment]
@SubhamPaul21 You have to delete the folders as they will not be deleted from the repo.

**Comment by SubhamPaul21** [comment]
@JimmyRooster Ok, I will do that. Thanks and closing the pull request.

**Comment by ghost** [comment]
Your not merging it?

**Comment by SubhamPaul21** [comment]
I will leave it for @HamdyElzonqali to fix if that is ok with him.

**Pull request closed without merging**
